
package de.localconvtemp;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ConvertTemperatureWebserviceService", targetNamespace = "http://webservice.server.ue9.tk1/", wsdlLocation = "http://localhost:8081/convert?wsdl")
public class ConvertTemperatureWebserviceService
    extends Service
{

    private final static URL CONVERTTEMPERATUREWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(de.localconvtemp.ConvertTemperatureWebserviceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = de.localconvtemp.ConvertTemperatureWebserviceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/convert?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/convert?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONVERTTEMPERATUREWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public ConvertTemperatureWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConvertTemperatureWebserviceService() {
        super(CONVERTTEMPERATUREWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://webservice.server.ue9.tk1/", "ConvertTemperatureWebserviceService"));
    }

    /**
     * 
     * @return
     *     returns LocalConvertTemperature
     */
    @WebEndpoint(name = "LocalConvertTemperaturePort")
    public LocalConvertTemperature getLocalConvertTemperaturePort() {
        return super.getPort(new QName("http://webservice.server.ue9.tk1/", "LocalConvertTemperaturePort"), LocalConvertTemperature.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocalConvertTemperature
     */
    @WebEndpoint(name = "LocalConvertTemperaturePort")
    public LocalConvertTemperature getLocalConvertTemperaturePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.server.ue9.tk1/", "LocalConvertTemperaturePort"), LocalConvertTemperature.class, features);
    }

}
