
package de.localconvtemp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LocalConvertTemperature", targetNamespace = "http://webservice.server.ue9.tk1/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LocalConvertTemperature {


    /**
     * 
     * @param fromUnit
     * @param toUnit
     * @param value
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "converted-value", partName = "converted-value")
    public double convert(
        @WebParam(name = "value", partName = "value")
        double value,
        @WebParam(name = "fromUnit", partName = "fromUnit")
        TemperatureUnit fromUnit,
        @WebParam(name = "toUnit", partName = "toUnit")
        TemperatureUnit toUnit);

}
