// This file was generated by mcc 1.0.1. DO NOT EDIT THIS FILE!
package tk1.ue13.agent;

public class MetaMandelAgent extends org.mundo.rt.Metaclass
{
  public String getExternalTypeName()
  {
    return "tk1.ue13.agent.MandelAgent";
  }
  public Class getJavaClass()
  {
    return tk1.ue13.agent.MandelAgent.class;
  }
  public String getFields()
  {
    return super.getFields()+"i[ mandelData;MandelConfig config;";
  }
  public tk1.ue13.agent.MandelAgent newInstance() throws InstantiationException 
  {
    return new tk1.ue13.agent.MandelAgent();
  }
  public void passivate(Object o, org.mundo.rt.TypedMap m) throws Exception
  {
    super.passivate(o, m);
    tk1.ue13.agent.MandelAgent t=(tk1.ue13.agent.MandelAgent)o;
    m.putPassivated("mandelData", t.mandelData);
    m.putPassivated("config", t.config);
  }
  public void activate(Object o, org.mundo.rt.TypedMap m, org.mundo.rt.TypedMap ctx) throws Exception
  {
    super.activate(o, m, ctx);
    tk1.ue13.agent.MandelAgent t=(tk1.ue13.agent.MandelAgent)o;
    try
    {
      t.mandelData=(int[])m.getActivated("mandelData", ctx);
    }
    catch(Exception x)
    {
      x.printStackTrace();
    }
    try
    {
      t.config=(MandelConfig)m.getActivated("config", ctx);
    }
    catch(Exception x)
    {
      x.printStackTrace();
    }
  }
}
