// This file was generated by mcc 1.0.1. DO NOT EDIT THIS FILE!
package tk.ue13.agent;

public class MetaMandelAgent extends org.mundo.rt.Metaclass
{
  public String getExternalTypeName()
  {
    return "tk.ue13.agent.MandelAgent";
  }
  public Class getJavaClass()
  {
    return tk.ue13.agent.MandelAgent.class;
  }
  public String getFields()
  {
    return super.getFields()+"";
  }
  public tk.ue13.agent.MandelAgent newInstance() throws InstantiationException 
  {
    return new tk.ue13.agent.MandelAgent();
  }
}
